/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.cabolabs.edu.openehr.archetypes

import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Option
import picocli.CommandLine.Parameters
import java.nio.file.Path

@Command
class App {

   static void main(String[] args)
   {
      //println "CWD "+ System.getProperty("user.dir")
      int rc = new CommandLine(new App()).execute(args)
      System.exit(rc)
   }

   @Command(
      name = 'parse',
      description = 'Parses a given archetype in ADL format'
   )
   public void parseCommand(
      @Parameters(arity = "1") Path pathToADL
   )
   {
      //println "parse archetype $pathToADL"
      def archetype = Services.parse(pathToADL)

      if (archetype)
      {
         println "Archetype parsed correctly."
         println "Archetype ID = "+ archetype.archetypeId
         println "Concept = "+ archetype.getConceptName('en')?.text
      }
   }

   @Command(
      name = 'traverse',
      description = 'Traverses a given archetype in ADL format'
   )
   public void traverseCommand(
      @Parameters(arity = "1") Path pathToADL
   )
   {
      def archetype = Services.traverse(pathToADL)
   }
}
