/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.cabolabs.edu.openehr.archetypes

import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Option
import picocli.CommandLine.Parameters
import java.nio.file.Path

@Command(name = 'archetypes')
class App {
   // String getGreeting() {
   //    return 'Hello World!'
   // }

   static void main(String[] args) {
      //println new App().greeting
      int rc = new CommandLine(new App()).execute(args)
      System.exit(rc)
   }

   @Command(
      name = 'parse',
      description = 'Parses a given archetype in ADL format'
   )
   public void parseCommand(
      @Parameters(arity = "1") Path pathToADL
   )
   {
      println "parse archetype $pathToADL"
   }
}
